# Generated by Django 5.1.1 on 2025-10-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_posts_comment_postlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postlink',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post'),
            preserve_default=False,
        ),
    ]
